import { DatabaseIR, Field } from "@repo/types";

const mapFieldTypeToPrisma = (type: string): string => {
  switch (type) {
    case "string": return "String";
    case "number": return "Int"; // Keeping it simple for MVP; could be Float
    case "boolean": return "Boolean";
    case "datetime": return "DateTime";
    case "json": return "Json";
    default: return "String";
  }
};

export const generatePrismaSchema = (database: DatabaseIR): string => {
  let schema = `// This file is auto-generated by Backend OS
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

  for (const model of database.models) {
    // Model Header
    schema += `model ${model.tableName.charAt(0).toUpperCase() + model.tableName.slice(1)} {\n`;

    // Fields
    model.fields.forEach((field: Field) => {
      // Skip relation fields in basic mapping, handle them via relations config if needed
      if (field.type === "relation") return; 
      
      const prismaType = mapFieldTypeToPrisma(field.type);
      const isId = field.name === model.primaryKey ? " @id @default(uuid())" : "";
      const isOptional = !field.required && !isId ? "?" : "";
      
      schema += `  ${field.name} ${prismaType}${isOptional}${isId}\n`;
    });

    // Relations (MVP: One-to-Many / Many-to-One rendering)
    model.relations.forEach((rel) => {
      if (rel.source === model.tableName) {
        // Source side of relation
        const targetModelName = rel.target.charAt(0).toUpperCase() + rel.target.slice(1);
        schema += `  ${rel.target.toLowerCase()}s ${targetModelName}[]\n`;
      } else if (rel.target === model.tableName) {
        // Target side of relation (Foreign Key)
        const sourceModelName = rel.source.charAt(0).toUpperCase() + rel.source.slice(1);
        schema += `  ${rel.source.toLowerCase()} ${sourceModelName} @relation(fields: [${rel.source.toLowerCase()}Id], references: [${rel.sourceField || 'id'}])\n`;
        schema += `  ${rel.source.toLowerCase()}Id String\n`; // Add foreign key field
      }
    });

    schema += `}\n\n`;
  }

  return schema.trim() + "\n";
};