import { ApiIR, CompiledRoute } from "@repo/types";

export interface RestArtifacts {
  server: string;
  routes: string;
  controllers: string;
}

export const generateRestAPI = (apis: ApiIR): RestArtifacts => {
  // 1. Generate Server Entry Point
  const server = `// server.js - Auto-generated by Backend OS
import express from 'express';
import cors from 'cors';
import { router } from './routes.js';

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// Register API Routes
app.use('/api', router);

app.listen(PORT, () => {
  console.log(\`Server running on http://localhost:\${PORT}\`);
});
`;

  // 2. Generate Routes
  let routes = `// routes.js - Auto-generated by Backend OS
import { Router } from 'express';
import * as controllers from './controllers.js';

export const router = Router();\n\n`;

  apis.routes.forEach((route: CompiledRoute) => {
    // e.g., router.get('/users', controllers.get_user);
    routes += `router.${route.method.toLowerCase()}('${route.path}', controllers.${route.handlerId});\n`;
  });

  // 3. Generate Controllers (with Prisma Boilerplate)
  let controllers = `// controllers.js - Auto-generated by Backend OS
import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();\n\n`;

  apis.routes.forEach((route: CompiledRoute) => {
    const entityName = route.entity.toLowerCase();
    
    controllers += `export const ${route.handlerId} = async (req, res) => {\n`;
    controllers += `  try {\n`;

    // Scaffold basic Prisma logic based on the action
    switch (route.action) {
      case "read":
        controllers += `    // Fetch records\n`;
        controllers += `    const data = await prisma.${entityName}.findMany();\n`;
        controllers += `    res.status(200).json(data);\n`;
        break;
      case "create":
        controllers += `    // Create record\n`;
        controllers += `    const data = await prisma.${entityName}.create({ data: req.body });\n`;
        controllers += `    res.status(201).json(data);\n`;
        break;
      case "update":
        controllers += `    // Update record (assuming ID is in params or body)\n`;
        controllers += `    const { id } = req.params; // Ensure path includes :id\n`;
        controllers += `    const data = await prisma.${entityName}.update({ where: { id }, data: req.body });\n`;
        controllers += `    res.status(200).json(data);\n`;
        break;
      case "delete":
        controllers += `    // Delete record\n`;
        controllers += `    const { id } = req.params; // Ensure path includes :id\n`;
        controllers += `    await prisma.${entityName}.delete({ where: { id } });\n`;
        controllers += `    res.status(204).send();\n`;
        break;
      default:
        controllers += `    res.status(501).json({ message: "Action not implemented" });\n`;
    }

    controllers += `  } catch (error) {\n`;
    controllers += `    console.error(error);\n`;
    controllers += `    res.status(500).json({ error: "Internal Server Error" });\n`;
    controllers += `  }\n`;
    controllers += `};\n\n`;
  });

  return { server, routes, controllers };
};